# Inserts a blank line between shell prompts
add_newline = true

# Replace the "❯" symbol in the prompt with "➜"
[character]
# success_symbol = "[ϻ](bold green)"
# error_symbol = "[ϻ](bold red)"
success_symbol = "[➜](bold green)"
error_symbol = "[➜](bold red)"

[line_break]
disabled = true